from app.models import db, Comment

def seed_comments():
    comment1 = Comment(comment_content='beep boop 🤖', user_id=6, post_id=2)
    comment2 = Comment(comment_content='yayy!! 🎉🎉', user_id=5, post_id=3)
    comment3 = Comment(comment_content='congrats my dude', user_id=8, post_id=3)
    comment4 = Comment(comment_content='nice', user_id=4, post_id=3)
    comment5 = Comment(comment_content='wow this is really amazing!', user_id=16, post_id=3)
    comment6 = Comment(comment_content='welcome!', user_id=17, post_id=4)
    comment7 = Comment(comment_content='this site\'s actually dope', user_id=2, post_id=5)
    comment8 = Comment(comment_content='sean pan, he\'s an up-and-coming pianist', user_id=3, post_id=6)
    comment9 = Comment(comment_content='he\'s got a YouTube channel, check it out', user_id=11, post_id=6)
    comment10 = Comment(comment_content='LISAAAAAAAA', user_id=18, post_id=8)
    comment11 = Comment(comment_content='Hi Lisa!', user_id=15, post_id=8)
    comment12 = Comment(comment_content='🔥🔥🔥', user_id=8, post_id=9)
    comment13 = Comment(comment_content='Hey how you doin?', user_id=2, post_id=10)
    comment14 = Comment(comment_content='You have a funny name 🤣', user_id=6, post_id=10)
    comment15 = Comment(comment_content='yeee', user_id=4, post_id=13)
    comment16 = Comment(comment_content='sure, my manager will contact you', user_id=5, post_id=18)
    comment17 = Comment(comment_content='awesome', user_id=9, post_id=18)
    comment18 = Comment(comment_content='Haha no worries!', user_id=10, post_id=20)
    comment19 = Comment(comment_content='it really is 🤩', user_id=15, post_id=17)
    comment20 = Comment(comment_content='Ay! Workin hard on my new album! Bouta bring some heat 🔥', user_id=8, post_id=21)
    comment21 = Comment(comment_content='awesome! looking forward to it', user_id=17, post_id=21)
    comment22 = Comment(comment_content='yeee I\'ll drop you the link when it\'s ready', user_id=8, post_id=21)
    comment23 = Comment(comment_content='bro just tell us', user_id=2, post_id=22)
    comment24 = Comment(comment_content='are you the real slim shady?', user_id=3, post_id=23)
    comment25 = Comment(comment_content='you already know', user_id=11, post_id=24)
    comment26 = Comment(comment_content='of course!! Jenny and I love you music too 🤩', user_id=6, post_id=26)
    comment27 = Comment(comment_content='IKR', user_id=15, post_id=27)
    comment28 = Comment(comment_content='Thank you 🤗', user_id=1, post_id=27)
    comment29 = Comment(comment_content='the legend himself', user_id=17, post_id=28)
    comment30 = Comment(comment_content='likewise, u a cool dude', user_id=18, post_id=29)
    comment31 = Comment(comment_content='where\'s billie jean at?', user_id=10, post_id=30)
    comment32 = Comment(comment_content='#king', user_id=9, post_id=30)
    comment33 = Comment(comment_content='hiii', user_id=7, post_id=33)
    comment34 = Comment(comment_content='producin these beats', user_id=3, post_id=35)
    comment35 = Comment(comment_content='hi kanye!', user_id=16, post_id=36)
    comment36 = Comment(comment_content='what\'s good ladies', user_id=4, post_id=36)
    comment37 = Comment(comment_content='soon...very soon', user_id=13, post_id=37)
    comment38 = Comment(comment_content='been spending more time with my brothers and sisters, hbu?', user_id=13, post_id=38)
    comment39 = Comment(comment_content='glad to hear you\'re spending more time with the fam', user_id=11, post_id=38)
    comment40 = Comment(comment_content='I\'ve been hanging out with Hailey more as well', user_id=11, post_id=38)
    comment41 = Comment(comment_content='😀', user_id=14, post_id=39)
    comment42 = Comment(comment_content='we love you girls too!!', user_id=5, post_id=41)
    comment43 = Comment(comment_content='blackpink in yo area!', user_id=4, post_id=41)
    comment44 = Comment(comment_content='NO YOU!', user_id=15, post_id=42)
    comment45 = Comment(comment_content='Thanks', user_id=16, post_id=43)
    comment46 = Comment(comment_content='haha appreciate it!', user_id=17, post_id=44)
    comment47 = Comment(comment_content='ikr it\'s so colorful 😮', user_id=15, post_id=45)
    comment48 = Comment(comment_content='hehe thanks girls 🤗', user_id=18, post_id=45)
    comment49 = Comment(comment_content='BARS', user_id=3, post_id=46)
    comment50 = Comment(comment_content='rip mgk', user_id=2, post_id=46)
    comment51 = Comment(comment_content='aite i come thru this weekend', user_id=2, post_id=48)
    comment52 = Comment(comment_content='i\'ll be there too', user_id=17, post_id=49)
    comment53 = Comment(comment_content='see you fools then', user_id=3, post_id=49)
    comment54 = Comment(comment_content='thanks you\'re so sweet 🤗', user_id=15, post_id=50)
    comment55 = Comment(comment_content='foreal tho', user_id=13, post_id=51)
    comment56 = Comment(comment_content='thanks y\'all!!', user_id=16, post_id=51)
    comment57 = Comment(comment_content='the eye of the tiger', user_id=17, post_id=52)
    comment58 = Comment(comment_content='oh snappp', user_id=10, post_id=52)
    comment59 = Comment(comment_content='ikr they\'re so catchy!', user_id=7, post_id=53)
    comment60 = Comment(comment_content='thanks!! 😀', user_id=18, post_id=53)
    comment61 = Comment(comment_content='sup', user_id=4, post_id=54)
    comment62 = Comment(comment_content='yayyy let\'s do it!!', user_id=5, post_id=55)
    comment63 = Comment(comment_content='wahh I wanna come 😭', user_id=6, post_id=55)
    comment64 = Comment(comment_content='yesss come come!', user_id=18, post_id=55)
    comment65 = Comment(comment_content='she\'s freee!!!!', user_id=15, post_id=56)
    comment66 = Comment(comment_content='Not as cute as you tho 😚', user_id=6, post_id=57)
    comment67 = Comment(comment_content='❤️❤️', user_id=7, post_id=58)
    comment68 = Comment(comment_content='taking a break from the music industry, just relax for a bit ya know?', user_id=9, post_id=59)
    comment69 = Comment(comment_content='for sure, do your thing', user_id=14, post_id=59)
    comment70 = Comment(comment_content='Thanks Gaga!', user_id=8, post_id=60)
    comment71 = Comment(comment_content='I wanna kick it with Luda 😩', user_id=10, post_id=61)
    comment72 = Comment(comment_content='sure come thru Taylor', user_id=11, post_id=61)
    comment73 = Comment(comment_content='yeah I\'ll see y\'all on Friday', user_id=9, post_id=61)
    comment74 = Comment(comment_content='Thanks Gaga! I miss you!', user_id=10, post_id=62)
    comment75 = Comment(comment_content='MG who?', user_id=11, post_id=63)
    comment76 = Comment(comment_content='lmao', user_id=3, post_id=63)
    comment77 = Comment(comment_content='thanks for the kind words', user_id=12, post_id=64)
    comment78 = Comment(comment_content='so are you Gaga', user_id=18, post_id=65)
    comment79 = Comment(comment_content='I agree with Billie', user_id=13, post_id=65)
    comment80 = Comment(comment_content='same', user_id=9, post_id=66)
    comment81 = Comment(comment_content='thanks guys', user_id=14, post_id=66)
    comment82 = Comment(comment_content='hi Billie! it was nice meeting you last night 🤗', user_id=10, post_id=67)
    comment83 = Comment(comment_content='Tiësto\'s always droppin bangers', user_id=5, post_id=68)
    comment84 = Comment(comment_content='thank you ladies', user_id=12, post_id=68)
    comment85 = Comment(comment_content='hi it\'s me!', user_id=14, post_id=69)
    comment86 = Comment(comment_content='woah it\'s Justin Beiber!', user_id=17, post_id=70)
    comment87 = Comment(comment_content='woohooo!!', user_id=7, post_id=71)
    comment88 = Comment(comment_content='chillin, gonna head to miami for a bit', user_id=8, post_id=72)
    comment89 = Comment(comment_content='cool story bro', user_id=9, post_id=72)
    comment90 = Comment(comment_content='I do too', user_id=17, post_id=73)
    comment91 = Comment(comment_content='appreciate it guys', user_id=9, post_id=73)
    comment92 = Comment(comment_content='writing rhymes', user_id=2, post_id=74)
    comment93 = Comment(comment_content='u a poet now?', user_id=17, post_id=74)
    comment94 = Comment(comment_content='the flyest one you know', user_id=2, post_id=74)
    comment95 = Comment(comment_content='somebody\'s salty lol', user_id=10, post_id=76)
    comment96 = Comment(comment_content='🤣🤣', user_id=8, post_id=76)
    comment97 = Comment(comment_content='thanks girl! 😘😘', user_id=5, post_id=77)
    comment98 = Comment(comment_content='norman\'s syringe got stuck in the orange door hinge', user_id=11, post_id=78)
    comment99 = Comment(comment_content='..thanks', user_id=3, post_id=78)
    comment100 = Comment(comment_content='?', user_id=16, post_id=79)
    comment101 = Comment(comment_content='you p-p-p-p-poker face', user_id=18, post_id=79)
    comment102 = Comment(comment_content='lol....', user_id=16, post_id=79)
    comment103 = Comment(comment_content='LOL', user_id=9, post_id=79)
    comment104 = Comment(comment_content='🤷🏽‍♂️', user_id=13, post_id=80)
    comment105 = Comment(comment_content='bro I was wondering the same thing...', user_id=4, post_id=80)
    comment106 = Comment(comment_content='it\'s a talent reserved for the king of pop', user_id=2, post_id=80)
    comment107 = Comment(comment_content='RED', user_id=6, post_id=81)
    comment108 = Comment(comment_content='red!', user_id=5, post_id=81)
    comment109 = Comment(comment_content='do blue next!', user_id=15, post_id=81)
    comment110 = Comment(comment_content='they\'re busy but they\'ll be here next month! let\'s hang out and take selfies 😁', user_id=6, post_id=82)
    comment111 = Comment(comment_content='yay!!!', user_id=5, post_id=82)
    comment112 = Comment(comment_content='where Jenny doe?', user_id=17, post_id=82)
    comment113 = Comment(comment_content='what up?', user_id=3, post_id=83)
    comment114 = Comment(comment_content='I got something to say', user_id=2, post_id=83)
    comment115 = Comment(comment_content='bye Mariah!', user_id=5, post_id=75)
    comment116 = Comment(comment_content='all I want for Christmas is yooOUuUuU', user_id=10, post_id=75)
    comment117 = Comment(comment_content='i can\'t wait to see you perform live again 🤗', user_id=15, post_id=40)


    db.session.add(comment1)
    db.session.add(comment2)
    db.session.add(comment3)
    db.session.add(comment4)
    db.session.add(comment5)
    db.session.add(comment6)
    db.session.add(comment7)
    db.session.add(comment8)
    db.session.add(comment9)
    db.session.add(comment10)
    db.session.add(comment11)
    db.session.add(comment12)
    db.session.add(comment13)
    db.session.add(comment14)
    db.session.add(comment15)
    db.session.add(comment16)
    db.session.add(comment17)
    db.session.add(comment18)
    db.session.add(comment19)
    db.session.add(comment20)
    db.session.add(comment21)
    db.session.add(comment22)
    db.session.add(comment23)
    db.session.add(comment24)
    db.session.add(comment25)
    db.session.add(comment26)
    db.session.add(comment27)
    db.session.add(comment28)
    db.session.add(comment29)
    db.session.add(comment30)
    db.session.add(comment31)
    db.session.add(comment32)
    db.session.add(comment33)
    db.session.add(comment34)
    db.session.add(comment35)
    db.session.add(comment36)
    db.session.add(comment37)
    db.session.add(comment38)
    db.session.add(comment39)
    db.session.add(comment40)
    db.session.add(comment41)
    db.session.add(comment42)
    db.session.add(comment43)
    db.session.add(comment44)
    db.session.add(comment45)
    db.session.add(comment46)
    db.session.add(comment47)
    db.session.add(comment48)
    db.session.add(comment49)
    db.session.add(comment50)
    db.session.add(comment51)
    db.session.add(comment52)
    db.session.add(comment53)
    db.session.add(comment54)
    db.session.add(comment55)
    db.session.add(comment56)
    db.session.add(comment57)
    db.session.add(comment58)
    db.session.add(comment59)
    db.session.add(comment60)
    db.session.add(comment61)
    db.session.add(comment62)
    db.session.add(comment63)
    db.session.add(comment64)
    db.session.add(comment65)
    db.session.add(comment66)
    db.session.add(comment67)
    db.session.add(comment68)
    db.session.add(comment69)
    db.session.add(comment70)
    db.session.add(comment71)
    db.session.add(comment72)
    db.session.add(comment73)
    db.session.add(comment74)
    db.session.add(comment75)
    db.session.add(comment76)
    db.session.add(comment77)
    db.session.add(comment78)
    db.session.add(comment79)
    db.session.add(comment80)
    db.session.add(comment81)
    db.session.add(comment82)
    db.session.add(comment83)
    db.session.add(comment84)
    db.session.add(comment85)
    db.session.add(comment86)
    db.session.add(comment87)
    db.session.add(comment88)
    db.session.add(comment89)
    db.session.add(comment90)
    db.session.add(comment91)
    db.session.add(comment92)
    db.session.add(comment93)
    db.session.add(comment94)
    db.session.add(comment95)
    db.session.add(comment96)
    db.session.add(comment97)
    db.session.add(comment98)
    db.session.add(comment99)
    db.session.add(comment100)
    db.session.add(comment101)
    db.session.add(comment102)
    db.session.add(comment103)
    db.session.add(comment104)
    db.session.add(comment105)
    db.session.add(comment106)
    db.session.add(comment107)
    db.session.add(comment108)
    db.session.add(comment109)
    db.session.add(comment110)
    db.session.add(comment111)
    db.session.add(comment112)
    db.session.add(comment113)
    db.session.add(comment114)
    db.session.add(comment115)
    db.session.add(comment116)
    db.session.add(comment117)




    db.session.commit()

def undo_comments():
    db.session.execute('TRUNCATE comments RESTART IDENTITY CASCADE;')
    db.session.commit()
