from app.models import db, Like

def seed_likes():
    post1 = Like(user_id=2, post_id=6)
    post2 = Like(user_id=3, post_id=6)
    post3 = Like(user_id=4, post_id=6)
    post4 = Like(user_id=2, post_id=4)
    post5 = Like(user_id=3, post_id=4)
    post6 = Like(user_id=2, post_id=5)
    post7 = Like(user_id=8, post_id=5)
    post8 = Like(user_id=3, post_id=3)
    post9 = Like(user_id=7, post_id=3)
    post10 = Like(user_id=9, post_id=3)
    post11 = Like(user_id=5, post_id=3)
    post12 = Like(user_id=6, post_id=2)
    post13 = Like(user_id=7, post_id=2)
    post14 = Like(user_id=8, post_id=2)
    post15 = Like(user_id=9, post_id=2)
    post16 = Like(user_id=10, post_id=2)
    post17 = Like(user_id=2, post_id=2)
    post18 = Like(user_id=5, post_id=1)
    post19 = Like(user_id=6, post_id=1)
    post20 = Like(user_id=7, post_id=1)

    comment1 = Like(user_id=6, comment_id=1)
    comment2 = Like(user_id=7, comment_id=1)
    comment3 = Like(user_id=4, comment_id=2)
    comment4 = Like(user_id=6, comment_id=3)
    comment5 = Like(user_id=5, comment_id=4)
    comment6 = Like(user_id=6, comment_id=4)
    comment7 = Like(user_id=4, comment_id=5)
    comment8 = Like(user_id=8, comment_id=5)
    comment9 = Like(user_id=9, comment_id=6)
    comment10 = Like(user_id=5, comment_id=6)
    comment11 = Like(user_id=6, comment_id=6)
    comment12 = Like(user_id=10, comment_id=6)
    comment13 = Like(user_id=7, comment_id=7)
    comment14 = Like(user_id=8, comment_id=7)
    comment15 = Like(user_id=3, comment_id=7)
    comment16 = Like(user_id=9, comment_id=8)
    comment17 = Like(user_id=8, comment_id=8)
    comment18 = Like(user_id=7, comment_id=8)
    comment19 = Like(user_id=6, comment_id=8)
    comment20 = Like(user_id=7, comment_id=9)
    comment21 = Like(user_id=11, comment_id=9)
    comment22 = Like(user_id=7, comment_id=14)
    comment23 = Like(user_id=6, comment_id=14)
    comment24 = Like(user_id=6, comment_id=12)



    db.session.add(post1)
    db.session.add(post2)
    db.session.add(post3)
    db.session.add(post4)
    db.session.add(post5)
    db.session.add(post6)
    db.session.add(post7)
    db.session.add(post8)
    db.session.add(post9)
    db.session.add(post10)
    db.session.add(post11)
    db.session.add(post12)
    db.session.add(post13)
    db.session.add(post14)
    db.session.add(post15)
    db.session.add(post16)
    db.session.add(post17)
    db.session.add(post18)
    db.session.add(post19)
    db.session.add(post20)

    db.session.add(comment1)
    db.session.add(comment2)
    db.session.add(comment3)
    db.session.add(comment4)
    db.session.add(comment5)
    db.session.add(comment6)
    db.session.add(comment7)
    db.session.add(comment8)
    db.session.add(comment9)
    db.session.add(comment10)
    db.session.add(comment11)
    db.session.add(comment12)
    db.session.add(comment13)
    db.session.add(comment14)
    db.session.add(comment15)
    db.session.add(comment16)
    db.session.add(comment17)
    db.session.add(comment18)
    db.session.add(comment19)
    db.session.add(comment20)
    db.session.add(comment21)
    db.session.add(comment22)
    db.session.add(comment23)
    db.session.add(comment24)
    # db.session.add(comment)
    # db.session.add(comment)

    db.session.commit()


def undo_likes():
    db.session.execute('TRUNCATE likes RESTART IDENTITY CASCADE;')
    db.session.commit()
