"""added columns to users table

Revision ID: 704b1969a165
Revises: 489a4564ea54
Create Date: 2021-12-20 01:26:06.427457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704b1969a165'
down_revision = '489a4564ea54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthday', sa.Date(), nullable=False))
    op.add_column('users', sa.Column('gender', sa.String(length=25), nullable=False))
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('education', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('work', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location')
    op.drop_column('users', 'work')
    op.drop_column('users', 'education')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'birthday')
    # ### end Alembic commands ###
