"""added profile_id column to post table

Revision ID: f99ac2367f5f
Revises: e0090fc2c42a
Create Date: 2021-12-16 10:46:20.468623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f99ac2367f5f'
down_revision = 'e0090fc2c42a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photos', 'createdAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('posts', sa.Column('profile_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'profile_id')
    op.alter_column('photos', 'createdAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
