"""created friends table

Revision ID: f47cae7d66d4
Revises: 704b1969a165
Create Date: 2021-12-21 13:59:48.560584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f47cae7d66d4'
down_revision = '704b1969a165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('friendAdder_id', sa.Integer(), nullable=False),
    sa.Column('friendReceiver_id', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['friendAdder_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['friendReceiver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'friendAdder_id', 'friendReceiver_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friend_list')
    # ### end Alembic commands ###
