"""added alias column

Revision ID: bdc90dd58733
Revises: 3d2455374385
Create Date: 2021-12-22 22:56:07.682398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdc90dd58733'
down_revision = '3d2455374385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('alias', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'alias')
    # ### end Alembic commands ###
