"""add picture column to post table

Revision ID: f1482c0a5fe4
Revises: bdc90dd58733
Create Date: 2022-01-08 18:44:21.462253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1482c0a5fe4'
down_revision = 'bdc90dd58733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('picture', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'picture')
    # ### end Alembic commands ###
